version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-lambda-template"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9aejc9nxm0im"
s3_prefix = "aws-lambda-template"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
