AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-template

  Sample SAM Template for aws-lambda-template
  
Parameters:
  CodeUri:
    Type: String
    Default: build/
  StageName:
    Type: String
    Default: Prod

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: app.handler
    Runtime: nodejs14.x
    Timeout: 3

Resources:
  # Project Http API
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Description: |
        Http API resource used by all Truck Control lambda functions
      DefaultRouteSettings:
        ThrottlingBurstLimit: 50

  NewPcbFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NewPcb
      CodeUri:  !Sub ${CodeUri}/newPcb/
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /pcb
            Method: POST

  # Function:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: 
  #     CodeUri:  !Sub ${CodeUri}/hello-world/
  #     Events:
  #       HelloWorld:
  #         Type: HttpApi
  #         Properties:
  #           ApiId: !Ref HttpApi
  #           Path: /
  #           Method: GET

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi
