AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-template

  Sample SAM Template for aws-lambda-template
  
Parameters:
  CodeUri:
    Type: String
    Default: build/
  StageName:
    Type: String
    Default: Prod

Globals:
  Function:
    Handler: app.handler
    Runtime: nodejs14.x
    Timeout: 3

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Description: |
        Example Http API
      DefaultRouteSettings:
        ThrottlingBurstLimit: 50

  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Example
      CodeUri:  !Sub ${CodeUri}/example/
      Events:
        Example:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /example
            Method: GET

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi
