name: CD
      
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # when there is a push to the master
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out to repository
      - uses: actions/checkout@v2
      
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - uses: aws-actions/setup-sam@v1

      - name: Building lambda functions of application
        run: ./build.sh
        shell: bash

      - name: SAM application build
        run: sam build
      
      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-region: 'us-east-1'
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: SAM application deployment
      #   run: sam deploy

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.8"
  #     - uses: aws-actions/setup-sam@v1

  #     - name: SAM application build
  #       run: sam build

      # - name: SAM Deploy
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-region: 'us-east-1'
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: SAM application deployment
      #   run: sam deploy
